from django.db import models

# Create your models here.
class agric_indicator(models.Model):
    ppp_sum =models.FloatField(null=True, blank=True, default=None)
    ndvi_jfm =models.FloatField(null=True, blank=True, default=None)
    ndvi_amj =models.FloatField(null=True, blank=True, default=None)
    ndvi_jas =models.FloatField(null=True, blank=True, default=None)
    ndvi_ond =models.FloatField(null=True, blank=True, default=None)
    ndwi_jfm =models.FloatField(null=True, blank=True, default=None)
    ndwi_amj =models.FloatField(null=True, blank=True, default=None)
    ndwi_jas =models.FloatField(null=True, blank=True, default=None)
    ndwi_ond =models.FloatField(null=True, blank=True, default=None)
    soil_phos =models.FloatField(null=True, blank=True, default=None)
    soil_copper =models.FloatField(null=True, blank=True, default=None)
    soil_iron =models.FloatField(null=True, blank=True, default=None)
    soil_magne =models.FloatField(null=True, blank=True, default=None)
    presp_jfm =models.FloatField(null=True, blank=True, default=None)
    presp_amj =models.FloatField(null=True, blank=True, default=None)
    presp_jas =models.FloatField(null=True, blank=True, default=None)
    presp_ond =models.FloatField(null=True, blank=True, default=None)
    soil_boron =models.FloatField(null=True, blank=True, default=None)
    soil_alumi =models.FloatField(null=True, blank=True, default=None)
    soil_potas =models.FloatField(null=True, blank=True, default=None)
    lst_jfm =models.FloatField(null=True, blank=True, default=None)
    lst_amj =models.FloatField(null=True, blank=True, default=None)
    lst_jas =models.FloatField(null=True, blank=True, default=None)
    lst_ond =models.FloatField(null=True, blank=True, default=None)
    slope =models.FloatField(null=True, blank=True, default=None)
    elevation =models.FloatField(null=True, blank=True, default=None)
    land_cover= models.IntegerField()
    gs_id=models.IntegerField()

    def save(self):
        self.ppp_sum = round(self.ppp_sum, 2)
        self.ndvi_jfm = round(self.ndvi_jfm, 2)
        self.ndvi_amj = round(self.ndvi_amj, 2)
        self.ndvi_jas = round(self.ndvi_jas, 2)
        self.ndvi_ond = round(self.ndvi_ond, 2)
        self.ndwi_jfm = round(self.ndwi_jfm, 2)
        self.ndwi_amj = round(self.ndwi_amj, 2)
        self.ndwi_jas = round(self.ndwi_jas, 2)
        self.ndwi_ond = round(self.ndwi_ond, 2)
        self.soil_phos = round(self.soil_phos, 2)
        self.soil_copper = round(self.soil_copper, 2)
        self.soil_iron = round(self.soil_iron, 2)
        self.soil_magne = round(self.soil_magne, 2)
        self.presp_jfm = round(self.presp_jfm, 2)
        self.presp_amj = round(self.presp_amj, 2)
        self.presp_jas = round(self.presp_jas, 2)
        self.presp_ond = round(self.presp_ond, 2)
        self.soil_boron = round(self.soil_boron, 2)
        self.soil_alumi = round(self.soil_alumi, 2)
        self.soil_potas = round(self.soil_potas, 2)
        self.lst_jfm = round(self.lst_jfm, 2)
        self.lst_amj = round(self.lst_amj, 2)
        self.lst_jas = round(self.lst_jas, 2)
        self.lst_ond = round(self.lst_ond, 2)
        
        return super(agric_indicator, self).save()
